[tox]
env_list = py312, py313, py314, py312-server

[testenv]
package = wheel
change_dir = {env_tmp_dir}
commands =
    python -W error::DeprecationWarning -m unittest discover -s {tox_root}/test -p "*_test.py"
    python -m tinman --help

[testenv:py312-server]
extras = server
commands =
    {[testenv]commands}
    python -m tinman server --help
